### ISSUE TITLE
[500] `lib/index.js` tries to import the typescript migrations resulting in an exception thrown.

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#175]
```
/Users/loicpoullain/Desktop/my-app/migrations/1534517004651-toto.ts:1
(function (exports, require, module, __filename, __dirname) { import {MigrationInterface, QueryRunner} from "typeorm";
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Function.PlatformTools.load (/Users/loicpoullain/Desktop/my-app/src/platform/PlatformTools.ts:110:28)
```

**Comment by LoicPoullain** [comment]
Fixed in v0.6.0-beta.3.
