### ISSUE TITLE
need help Cannot find module './lib/colors'

### ISSUE THREAD

**Issue by jcpc91** [FoalTS/foal#350]
MacBook-Pro: foal createapp my-app
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './lib/colors'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@foal/cli/node_modules/colors/safe.js:9:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by LoicPoullain** [comment]
Hi @jcpc91 

Thanks for reporting this.

Could you update npm and reinstall the CLI again to see what happens?
```
npm install -g npm
npm install -g @foal/cli
```

If this is not working, you may also try this:
```
npm uninstall -g @foal/cli
npm install -g @foal/cli
```

Could you also give me the version of your node executable? Did you use nvm for installing node or did you just download the "installer" from nodejs.org ?

```
node --version
```

Thanks

**Comment by jcpc91** [comment]
thanks for the answer that's work
sorry for my english i don´t speak
