### ISSUE TITLE
Decorators Inheritance Problem

### ISSUE THREAD

**Issue by kingdun3284** [FoalTS/foal#459]
I try to write a base controller which provide basic CRUD operation, but the decorators on it failed. Not just the @ValidateBody failed, @ApiRequestBody will fail as well. 

A controller:
```typescript
import { ApiDefineSchema, IApiSchema, dependency } from '@foal/core';
import { SomeEntity } from '../../entities/some.entity';
import { BaseController } from '../base.controller';
import { SomeService } from '../service/some.service';
export const someSchema = {
  type: 'object',
  properties: {
    name: {
      type: "string"
    }
  }
} as IApiSchema
@ApiDefineSchema('someModel', someSchema)
export class SomeController extends BaseController{
  @dependency
  service:SomeService
  constructor(){
    super(SomeEntity,someSchema)
  }
}

```
Base Controller:
```typescript
import { Context, HttpResponseCreated, ValidateBody, ApiRequestBody, ApiParameter, HttpResponseNotFound, Patch, dependency, Delete, HttpResponse, Post, Get } from '@foal/core';
import { getRepository } from 'typeorm';

export class BaseController {
  @dependency
  service
  entity;
  schema;
  constructor(entity, schema) {
    this.entity = entity;
    this.schema = schema;
  }
  @Post('/')
  @ValidateBody(this.schema)
  @ApiRequestBody({
    content: {
      "application/json": {
        schema: this.schema  
      }
    },
    required: true
  })
  async create(ctx: Context): Promise<HttpResponse> {
    let result = await this.service.create(ctx.request.body);
    return new HttpResponseCreated(result);
  }
  @Get('/')
  async findAll(): Promise<HttpResponse> {
    let repository = await getRepository(this.entity);
    const result= await repository.find();
    return new HttpResponseCreated(result);
  }

  @Get('/:id')
  @ApiParameter({
    in: "path",
    name: "id",
    required: true,
    schema: { type: "integer" }
  })
  async findById(ctx: Context): Promise<HttpResponse> {
    let result = await this.service.findById(ctx.request.params.id)
    if (result)
      return new HttpResponseCreated(result);
    return new HttpResponseNotFound();
  }

  @Patch('/:id')
  @ApiParameter({
    in: "path",
    name: "id",
    required: true,
    schema: { type: "integer" }
  })
  @ApiRequestBody({
    content: {
      "application/json": {
        schema: this.schema
      }
    },
    required: true
  })

  async update(ctx: Context): Promise<HttpResponse> {
    let result = await this.service.update(ctx.request.params.id, ctx.request.body)
    if (result)
      return new HttpResponseCreated(result);
    return new HttpResponseNotFound();
  }
  @Delete('/:id')
  @ApiParameter({
    in: "path",
    name: "id",
    required: true,
    schema: { type: "integer" }
  })
  async deleteById(ctx: Context): Promise<HttpResponse> {
    let result = await this.service.deleteById(ctx.request.params.id)
    if (result)
      return new HttpResponseCreated();
    return new HttpResponseNotFound();
  }
}
```

Errors:
```
 throw new Error('schema should be object or boolean');
[1]           ^
[1] Error: schema should be object or boolean
[1]     at Ajv._addSchema (C:\Users\Mathew\Documents\foal-playground\node_modules\ajv\lib\ajv.js:292:11)
[1]     at Ajv.compile (C:\Users\Mathew\Documents\foal-playground\node_modules\ajv\lib\ajv.js:112:24)
[1]     at Object.ValidateBody (C:\Users\Mathew\Documents\foal-playground\node_modules\@foal\core\lib\common\hooks\validate-body.hook.js:14:25)
[1]     at Object.<anonymous> (C:\Users\Mathew\Documents\foal-playground\src\app\controllers\base.controller.ts:14:4)
[1]     at Module._compile (internal/modules/cjs/loader.js:774:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
[1]     at Module.load (internal/modules/cjs/loader.js:641:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
[1]     at Module.require (internal/modules/cjs/loader.js:681:19)
[1]     at require (internal/modules/cjs/helpers.js:16:16)
[1] Program node ./build/index.js exited with code 1
[1]
```

**Comment by LoicPoullain** [comment]
Thanks for reporting this!

You were right, both issues (the `@ValidateBody` hook and the OpenAPI decorator) comes from the fact that `this.schema` is evaluated at build-time. The solution I found would be to evaluate it at runtime.

## Proposal for the hook issue (`@ValidateBody`)

Bind the `this` to each hook function so as to be able to access the (child) controller at runtime.

*Simple case (currently supported and will still be supported with the new feature)*
```typescript
class MyController {

  @Hook((ctx: Context, services: ServiceManager) => {
    // ...
  })
  foo() {
    // ...
  }

}
```

*Case where we get access to the `this` which is actually the controller*
```typescript
class MyController {

  @Hook((this: MyController, ctx: Context, services: ServiceManager) => {
    // Do some stuff with this.xxx . `this` is not undefined.
  })
  foo() {
    // ...
  }

}
```

With this proposal we can extend each `@Validate` hook to accept a function.

*Simple case*
```typescript
class MyController {

  @ValidateBody(mySchema)
  foo() {
    // ...
  }

}
```

*Case where we access the schema during the hook execution (**solution of the issue**).*
```typescript
class MyController {

  constructor(schema) {
    this.schema = schema;
  }

  @ValidateBody(this => this.schema)
  foo() {
    // ...
  }

}
```

## Proposal for the OpenAPI decorator

In similar way, `@ApiRequestBody(this => this.schema)`. This one will be a bit more complicated to implement due to how the framework is structured. But this can be done.

## Small shortcut in TypeScript

Not related to the issues, but if it can help, here is a small shortcut in TS to define and assign properties in the constructor:

```typescript
class Foo {
  entity;
  schema;
  constructor(entity, schema) {
    this.entity = entity;
    this.schema = schema;
  }
}
// is equivalent to
class Foo {
  constructor(public entity, public schema) { }
}
```

**Comment by LoicPoullain** [comment]
I just merged the PR fixing this. It will be released with version 1 this week!

Link to the acceptance test: https://github.com/FoalTS/foal/blob/june-release/packages/acceptance-tests/src/controller-inheritance.spec.ts.
