### ISSUE TITLE
password filed error

### ISSUE THREAD

**Issue by sumanadak** [FoalTS/foal#674]
I am getting this error when I try to register an user

TypeError [ERR_INVALID_ARG_TYPE]: The "password" argument must be one of type string, Buffer, TypedArray, or DataView. Received type undefined
at check (internal/crypto/pbkdf2.js:67:14)
at pbkdf2 (internal/crypto/pbkdf2.js:26:5)
at internal/util.js:278:30
at new Promise ()
at pbkdf2 (internal/util.js:277:12)
at Object.hashPassword (/home/suman/personal-projects/photo-manager/node_modules/@foal/core/lib/common/utils/hash-password.util.js:40:69)
at User.setPassword (/home/suman/personal-projects/photo-manager/src/app/entities/user.entity.ts:19:22)
at async Promise.all (index 0)

can someone please help on this ?

**Comment by LoicPoullain** [comment]
Hi @sumanadak 

We will need more information to solve your error.

What is your code? What is the password value you pass as argument?

**Comment by LoicPoullain** [comment]
I am closing the issue because there has been no response to the last comment in the last thee weeks. Feel free to reopen it if you still need help @sumanadak 👍 .

**Comment by sumanadak** [comment]
I am sorry for late reply.

It was my mistake.

Thanks
Suman
