### ISSUE TITLE
creating a new project and running it results into an error

### ISSUE THREAD

**Issue by PatrickJung94** [FoalTS/foal#704]
Following the tutorial and creating a new app you will see an error once you want to start the app.

I am using Version 1.7.1 but it still happens on 1.8.1.

`foal createapp test`

`cd test`

`npm run develop`

Will result into following error:

```
 /Users/patrickjung/Documents/backendProjects/test/src/index.ts:141
 export {EntityManager} from "./entity-manager/EntityManager";
         ^
 TypeError: Cannot set property EntityManager of #<Object> which has only a getter
     at Object.<anonymous> (/Users/patrickjung/Documents/backendProjects/test/src/index.ts:141:9)
     at Module._compile (internal/modules/cjs/loader.js:776:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
     at Module.load (internal/modules/cjs/loader.js:653:32)
     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
     at Module.require (internal/modules/cjs/loader.js:690:17)
     at require (internal/modules/cjs/helpers.js:25:18)
     at Object.<anonymous> (/Users/patrickjung/Documents/backendProjects/test/src/index.ts:8:1)
     at Module._compile (internal/modules/cjs/loader.js:776:30)
 Program node ./build/index.js exited with code 1
```
I do not seem to find EntityManager in the generated files.

**Comment by Till92921** [comment]
First of all nice Framework!

Unfortunately i got the same mistake today.

**Comment by PatrickJung94** [comment]
I tried to compare the package-lock.json of a working project with the newly generated one and I noticed that `acorn` updated from `7.1.1` to `7.2.0`. Could this be the cause?

**Comment by LoicPoullain** [comment]
Thanks for reporting the issue @PatrickJung94 

It looks like it comes from TypeORM which depends on `tslib` which seems to fail on the latest version. Would running `npm i tslib@1.11.2` solve the problem?

**Comment by PatrickJung94** [comment]
@LoicPoullain Thanks this fixed the issue.

**Comment by LoicPoullain** [comment]
It looks like the issue has been fixed since (https://github.com/microsoft/tslib/issues/103#issuecomment-628297050). Feel free to re-open the issue if it hasn't
