### ISSUE TITLE
Can some please tell me the correct format for enums in migration

### ISSUE THREAD

**Issue by shellac85** [FoalTS/foal#739]
I am trying to run a migration, adding enum values to a table in a postres db. But when I try build the code, in AWS logs I am getting this error
```
{ QueryFailedError: syntax error at or near "credit"
    at new QueryFailedError (/app/src/error/QueryFailedError.ts:9:9)
    at Query.callback (/app/src/driver/postgres/PostgresQueryRunner.ts:176:30)
    at Query.handleError (/app/node_modules/pg/lib/query.js:142:17)
    at Connection.connectedErrorMessageHandler (/app/node_modules/pg/lib/client.js:194:17)
    at Connection.emit (events.js:182:13)
    at Connection.EventEmitter.emit (domain.js:442:20)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:126:12)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
  message: 'syntax error at or near "credit"',
  name: 'QueryFailedError',
  length: 95,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '49',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1128',
  routine: 'scanner_yyerror',
  query:
   'CREATE TYPE "customer_paymenttype_enum" AS ENUM(credit, sepa, other, monthlyInvoice)',
  parameters: [] }
```
I have tried double quotes and no quotes. Both get erros. Whats the proper way to solve this please?
```
import { MigrationInterface, QueryRunner } from 'typeorm';

export class CustomerPaymentTypes1592475742419 implements MigrationInterface {
  public async up(queryRunner: QueryRunner) {
    await queryRunner.query('ALTER TYPE "customer_paymenttype_enum" RENAME TO "customer_paymenttype_enum_old"');
    await queryRunner.query('CREATE TYPE "customer_paymenttype_enum" AS ENUM(credit, sepa, other, monthlyInvoice)');
    await queryRunner.query('ALTER TABLE "customer" ALTER COLUMN "paymentType" TYPE "customer_paymenttype_enum" USING "paymentType"::"text"::"customer_paymenttype_enum"');
    await queryRunner.query('DROP TYPE "customer_paymenttype_enum_old"');
    await queryRunner.query('ALTER TABLE "customer" ALTER COLUMN "isOverdue" SET NOT NULL');
  }

  public async down(queryRunner: QueryRunner) {
    await queryRunner.query('ALTER TABLE "customer" ALTER COLUMN "isOverdue" DROP NOT NULL');
    await queryRunner.query('CREATE TYPE "customer_paymenttype_enum_old" AS ENUM(credit, sepa)');
    await queryRunner.query('ALTER TABLE "customer" ALTER COLUMN "paymentType" TYPE "customer_paymenttype_enum_old" USING "paymentType"::"text"::"customer_paymenttype_enum_old"');
    await queryRunner.query('DROP TYPE "customer_paymenttype_enum"');
    await queryRunner.query('ALTER TYPE "customer_paymenttype_enum_old" RENAME TO "customer_paymenttype_enum"');
  }
}
```

**Comment by LoicPoullain** [comment]
@shellac85 did you generate your migrations locally using SQLite or a PostgreSQL?

**Comment by shellac85** [comment]
Hi,

I actually fixed this if anyone else has the same problem. Basically Postgress needs the enum vales with single quotes: 'credit'

So in the migration I did this: \'credit\'

Thanks for getting back to me though!
