### ISSUE TITLE
(foal CLI) TypeError: Cannot set property 'proxyConfig' of undefined

### ISSUE THREAD

**Issue by lcnvdl** [FoalTS/foal#982]
Version of FoalTS: 2.5.0

Steps:
1. foal createapp portal
2. npm i -g @angular/cli
3. ng new portal-frontend
4. cd portal
5. foal connect angular ../portal-frontend

Error:
```
C:\Users\Luciano\Documents\GitHub\forjagames-portal\portal>foal connect angular ../portal-frontend
CREATE ..\portal-frontend\src\proxy.conf.json
UPDATE ..\portal-frontend\package.json
UPDATE ..\portal-frontend\angular.json
(node:5548) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'proxyConfig' of undefined
    at C:\Users\Luciano\AppData\Roaming\npm\node_modules\@foal\cli\lib\generate\generators\angular\connect-angular.js:38:84
    at FileSystem.modify (C:\Users\Luciano\AppData\Roaming\npm\node_modules\@foal\cli\lib\generate\file-system.js:245:46)
    at Object.connectAngular (C:\Users\Luciano\AppData\Roaming\npm\node_modules\@foal\cli\lib\generate\generators\angular\connect-angular.js:35:10)
    at Command.<anonymous> (C:\Users\Luciano\AppData\Roaming\npm\node_modules\@foal\cli\lib\index.js:67:24)
    at Command.listener [as _actionHandler] (C:\Users\Luciano\AppData\Roaming\npm\node_modules\@foal\cli\node_modules\commander\index.js:922:31)
    at Command._parseCommand (C:\Users\Luciano\AppData\Roaming\npm\node_modules\@foal\cli\node_modules\commander\index.js:1503:14)
    at Command._dispatchSubcommand (C:\Users\Luciano\AppData\Roaming\npm\node_modules\@foal\cli\node_modules\commander\index.js:1443:18)    
    at Command._parseCommand (C:\Users\Luciano\AppData\Roaming\npm\node_modules\@foal\cli\node_modules\commander\index.js:1460:12)
    at Command.parse (C:\Users\Luciano\AppData\Roaming\npm\node_modules\@foal\cli\node_modules\commander\index.js:1292:10)
    at Object.<anonymous> (C:\Users\Luciano\AppData\Roaming\npm\node_modules\@foal\cli\lib\index.js:152:9)
(node:5548) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5548) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by LoicPoullain** [comment]
Thank your for reporting this issue @lcnvdl . A fix is on its way 👍

**Comment by LoicPoullain** [comment]
Fixed in v2.6.0

**Comment by lcnvdl** [comment]
Thank you very much!!

**Comment by lcnvdl** [comment]
Hello again. Do you know when the version 2.6.0 will be published?

I'm asking you this because I'm making a couple of videos about FoalTS, and I'm waiting for this feature to continuo.

Thank you very much!

Best regards,
LR

**Comment by LoicPoullain** [comment]
> Do you know when the version 2.6.0 will be published?

This week or next week.

> I'm asking you this because I'm making a couple of videos about FoalTS, and I'm waiting for this feature to continue.

Oh glad to hear it! Feel free to share your videos on the [awesome page](https://foalts.org/docs/community/awesome-foal/) when they're published 👍
