### ISSUE TITLE
No repository for "xxx" was found. Looks like this entity is not registered in current "default" connection?

### ISSUE THREAD

**Issue by martinsnihur** [FoalTS/foal#997]
Version of FoalTS: 
2.6.0

I use foal g rest-api <name> to create a new controller and a new entity and then "npm run develop" is executed without errors, but when accessing the newly created controller, the error occurs:
"No repository for "xxx" was found. Looks like this entity is not registered in current" default "connection?"

Database: PostgreSQL
Details:
-------------------------------------- 
[1] |                                      |
[1] |                                      |
[1] |            Server started!           |
[1] |                                      |
[1] |     Local: http://localhost:3001     |
[1] |                                      |
[1] |                                      |
[1]  -------------------------------------- 
[1]
[1] RepositoryNotFoundError: No repository for "Pais" was found. Looks like this entity is not registered in current "default" connection?
[1]     at new RepositoryNotFoundError (C:\Users\MARTIN-PAO\Desarrollo\TurnosApp\turnos-rest\src\error\RepositoryNotFoundError.ts:10:9)        
[1]     at EntityManager.getRepository (C:\Users\MARTIN-PAO\Desarrollo\TurnosApp\turnos-rest\src\entity-manager\EntityManager.ts:1193:19)      
[1]     at Connection.getRepository (C:\Users\MARTIN-PAO\Desarrollo\TurnosApp\turnos-rest\src\connection\Connection.ts:342:29)
[1]     at Object.getRepository (C:\Users\MARTIN-PAO\Desarrollo\TurnosApp\turnos-rest\src\index.ts:287:55)
[1]     at PaisController.findPaiss (C:\Users\MARTIN-PAO\Desarrollo\TurnosApp\turnos-rest\src\app\controllers\v1\pais.controller.ts:35:25)     
[1]     at Object.getResponse (C:\Users\MARTIN-PAO\Desarrollo\TurnosApp\turnos-rest\node_modules\@foal\core\lib\core\routes\get-response.js:27:65)
[1]     at C:\Users\MARTIN-PAO\Desarrollo\TurnosApp\turnos-rest\node_modules\@foal\core\lib\express\create-app.js:86:34

**Comment by LoicPoullain** [comment]
Hi @martinsnihur 

Have you generated and run migrations?

**Comment by martinsnihur** [comment]
Hello, 
no, I have the database already created previously, the table exists.

**Comment by LoicPoullain** [comment]
Could it be a case problem with your imports? https://stackoverflow.com/a/58704642

**Comment by LoicPoullain** [comment]
I'm closing the issue as there has been no response to the last comment in the last three months. Feel free to reach back if you still need help on this 👍
